services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["npm", "run", "dev", "--", "--host"] 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=3ruTPH~#StjH4q`zTq@e
      - MYSQL_DATABASE=dbname

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: maindb
      MYSQL_USER: user
      MYSQL_PASSWORD: 3ruTPH~#StjH4q`zTq@e
      MYSQL_ROOT_PASSWORD: x^iRoTtF&DY#gV43non5
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:

